### ISSUE TITLE
Add a new application

### ISSUE THREAD

**Issue by sabkaraja** [nenad-zivkovic/yii2-advanced-template#24]
Hi

How to add a new application (in addition to frontend, backend, console) under the main project bundle.

The way I did was copy root backend & _protected/backend as **mobile** and changing the name spaces backend to api.

But when I launch the site as http://localhost/demo/mobile/, I get the following error 

> An Error occurred while handling another error:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "site/error".' in C:\WAMP\www\demo\ _protected\vendor\yiisoft\yii2\base\Module.php:461
Stack trace:
#0 C:\WAMP\www\demo\ _protected\vendor\yiisoft\yii2\web\ErrorHandler.php(85): yii\base\Module->runAction('site/error')
#1 C:\WAMP\www\demo\ _protected\vendor\yiisoft\yii2\base\ErrorHandler.php(109): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
> Previous exception:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "site/login".' in C:\WAMP\www\demo\ _protected\vendor\yiisoft\yii2\base\Module.php:461
Stack trace:
#0 C:\WAMP\www\demo\ _protected\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('site/login', Array)
#1 C:\WAMP\www\demo\ _protected\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 C:\WAMP\www\demo\mobile\index.php(18): yii\base\Application->run()
#3 {main}
> Next exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in C:\WAMP\www\demo\ _protected\vendor\yiisoft\yii2\web\Application.php:96
Stack trace:
#0 C:\WAMP\www\demo\ _protected\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 C:\WAMP\www\demo\mobile\index.php(18): yii\base\Application->run()
#2 {main}

**Comment by sabkaraja** [comment]
Spoke too early. I hadnt changed the \common\config\bootstrap.php to include the newly added application

> Yii::setAlias('mobile', dirname(dirname(__DIR__)) . '/mobile');

Now its working.
